server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4j Circuit Breaker Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5

  timelimiter:
    configs:
      default:
        timeout-duration: 3s
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    urls:
#      - name: Product Service
#        url: /aggregate/product-service/v3/api-docs
#      - name: Customer Service
#        url: /customer/product-service/v3/api-docs
#      - name: Order Service
#        url: /aggregate/order-service/v3/api-docs
#      - name: Payment Service
#        url: /aggregate/payment-service/v3/api-docs
#      - name: Notification Service
#        url: /aggregate/notification-service/v3/api-docs
#  api-docs:
#    path: /api-docs